import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import { get } from "axios";

const initialState = {
  loading: false,
  users: [],
  error: "",
};

/**
 * 1st arg is action type
 * 2nd arg is callback function that creates the payload
 */

//  will automatically dispatch lifecycle actions based on the returned promise
//  a promise is either pending, fulfilled or rejected

// Generated pending, fulfilled, rejected action types
// can listen to these action types in a reducer function
// these reducers are not generated by the createSlice so need to add
// them as extra reducers
export const fetchUsers = createAsyncThunk("user/fetchUsers", () => {
  return get("https://jsonplaceholder.typicode.com/users").then(
    (response) => response.data
  );
  // no need to add catch as errors handled automatically
});

const userSlice = createSlice({
  name: "user",
  initialState,
  extraReducers: (builder) => {
    builder.addCase(fetchUsers.pending, (state) => {
      state.loading = true;
    });
    builder.addCase(fetchUsers.fulfilled, (state, action) => {
      state.loading = false;
      state.users = action.payload;
      state.error = "";
    });
    builder.addCase(fetchUsers.rejected, (state, action) => {
      state.loading = false;
      state.users = [];
      state.error = action.error.message;
    });
  },
});

export default userSlice.reducer;
